/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import codeScript from "./game/codeScript"
import Button from "./game/Button"
import home from "./game/home"
import WidgScrpit from "./game/WidgScrpit"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1136;
    static height:number=640;
    static scaleMode:string="fixedheight";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="codeSence.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/codeScript.ts",codeScript);
        reg("game/Button.ts",Button);
        reg("game/home.ts",home);
        reg("game/WidgScrpit.ts",WidgScrpit);
    }
}
GameConfig.init();